# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IgorItemClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3)),
                ('label', models.CharField(blank=True, default=b'', max_length=64)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProductHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hierarchy.Parent')),
            ],
            bases=('hierarchy.parent',),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hierarchy.Parent')),
            ],
            bases=('hierarchy.parent',),
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hierarchy.Parent')),
            ],
            bases=('hierarchy.parent',),
        ),
        migrations.CreateModel(
            name='ProductLineGroup',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hierarchy.Parent')),
            ],
            bases=('hierarchy.parent',),
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hierarchy.Parent')),
            ],
            bases=('hierarchy.parent',),
        ),
        migrations.CreateModel(
            name='SubBusinessUnit',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hierarchy.Parent')),
            ],
            bases=('hierarchy.parent',),
        ),
        migrations.CreateModel(
            name='SubProductLine',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hierarchy.Parent')),
            ],
            bases=('hierarchy.parent',),
        ),
    ]
