#!/usr/bin/env python
import os
import base64
from pdb import set_trace as debug
import urllib
import glob


#Reset the database
from django.conf import settings
from django.core.wsgi import get_wsgi_application
os.environ['DJANGO_SETTINGS_MODULE'] = 'project.settings'
application = get_wsgi_application()
from django import setup
try:
    os.chdir(os.path.dirname(__file__))
except OSError:
    pass
setup()
from hierarchy.views import *


from django.core.urlresolvers import reverse
from django.test import Client


removeFiles = [
    os.path.abspath("db.sqlite3"),
    os.path.abspath(os.path.join("hierarchy", "migrations", "0*.py")),
    os.path.abspath(os.path.join("hierarchy", "migrations", "*.pyc")),
    ]

for removeFile in removeFiles:
    for filename in glob.glob(removeFile):
        os.remove(filename)

commands = """python manage.py makemigrations hierarchy
python manage.py migrate
python manage.py loaddata {0}
python misc.py --codes""".format(os.path.join("hierarchy", "fixtures", "auth.json")).split("\n")
print commands



for command in commands:
    os.system(command)
