#!/usr/bin/env python
import os
import base64
from pdb import set_trace as debug
import urllib


#Reset the database
from django.conf import settings
from django.core.wsgi import get_wsgi_application
os.environ['DJANGO_SETTINGS_MODULE'] = 'project.settings'
application = get_wsgi_application()
from django import setup
try:
    os.chdir(os.path.dirname(__file__))
except OSError:
    pass
setup()
from hierarchy.views import *


from django.core.urlresolvers import reverse
from django.test import Client




commands = """rm db.sqlite3
rm hierarchy/migrations/0*.py
rm hierarchy/migrations/*.pyc
./manage.py makemigrations hierarchy
./manage.py migrate""".split("\n")


for command in commands:
    os.system(command)

import pexpect

os.system("./manage.py loaddata hierarchy/fixtures/auth.json")
os.system("./misc.py --codes")
print
